//
// Generated file, do not edit! Created by opp_msgtool 6.4 from CustomerPacket.msg.
//

#ifndef __MMCLQUEUEINGSIMULATION_CUSTOMERPACKET_M_H
#define __MMCLQUEUEINGSIMULATION_CUSTOMERPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0604
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace mmclqueueingsimulation {

class CustomerPacket;

}  // namespace mmclqueueingsimulation


namespace mmclqueueingsimulation {

/**
 * Class generated from <tt>CustomerPacket.msg:7</tt> by opp_msgtool.
 * <pre>
 * packet CustomerPacket
 * {
 *     simtime_t arrivalInstant;
 * }
 * </pre>
 */
class CustomerPacket : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::simtime_t arrivalInstant = SIMTIME_ZERO;

  private:
    void copy(const CustomerPacket& other);

  protected:
    bool operator==(const CustomerPacket&) = delete;

  public:
    CustomerPacket(const char *name=nullptr, short kind=0);
    CustomerPacket(const CustomerPacket& other);
    virtual ~CustomerPacket();
    CustomerPacket& operator=(const CustomerPacket& other);
    virtual CustomerPacket *dup() const override {return new CustomerPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual ::omnetpp::simtime_t getArrivalInstant() const;
    virtual void setArrivalInstant(::omnetpp::simtime_t arrivalInstant);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CustomerPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CustomerPacket& obj) {obj.parsimUnpack(b);}


}  // namespace mmclqueueingsimulation


namespace omnetpp {

template<> inline mmclqueueingsimulation::CustomerPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<mmclqueueingsimulation::CustomerPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MMCLQUEUEINGSIMULATION_CUSTOMERPACKET_M_H

